/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssociationsRouteImport } from './routes/associations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BayAreaIconsRouteImport } from './routes/bay-area-icons'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CredaiHyderabad2026RouteImport } from './routes/credai-hyderabad-2026'
import { Route as CredaiShowRouteImport } from './routes/credai-show'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DirectoryIngestRouteImport } from './routes/directory-ingest'
import { Route as EpaperRouteImport } from './routes/epaper'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FoodRouteImport } from './routes/food'
import { Route as FoodIngestRouteImport } from './routes/food-ingest'
import { Route as FoodMergeRouteImport } from './routes/food-merge'
import { Route as FoundationIconsRouteImport } from './routes/foundation-icons'
import { Route as GlamourDashboardRouteImport } from './routes/glamour-dashboard'
import { Route as LiteRouteImport } from './routes/lite'
import { Route as LocalDirectoryRouteImport } from './routes/local-directory'
import { Route as LuxedeskRouteImport } from './routes/luxedesk'
import { Route as NriRealEstateRouteImport } from './routes/nri-real-estate'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as PropertyDeskRouteImport } from './routes/property-desk'
import { Route as PropertyVideosRouteImport } from './routes/property-videos'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDirectoryDotxmlRouteImport } from './routes/sitemap-directory[.]xml'
import { Route as SitemapNewsDotxmlRouteImport } from './routes/sitemap-news[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TempleSourcesRouteImport } from './routes/temple-sources'
import { Route as TemplesRouteImport } from './routes/temples'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as CityCityRouteImport } from './routes/city.$city'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as DirectorySlugRouteImport } from './routes/directory.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsTempleCalendarRouteImport } from './routes/events.temple-calendar'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as FoodAddRouteImport } from './routes/food.add'
import { Route as FoodDealsRouteImport } from './routes/food.deals'
import { Route as FoodRestaurantsRouteImport } from './routes/food.restaurants'
import { Route as ForumsIndexRouteImport } from './routes/forums/index'
import { Route as PropertyIndexRouteImport } from './routes/property.index'
import { Route as PropertyCampaignRouteImport } from './routes/property.$campaign'
import { Route as TemplesIndexRouteImport } from './routes/temples.index'
import { Route as TemplesCityRouteImport } from './routes/temples.$city'
import { Route as TemplesCalendarRouteImport } from './routes/temples.calendar'
import { Route as TemplesNewsRouteImport } from './routes/temples.news'
import { Route as AuthenticatedAdminDriveImportRouteImport } from './routes/_authenticated/admin.drive-import'
import { Route as AuthenticatedAdminDuplicatesRouteImport } from './routes/_authenticated/admin.duplicates'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as ApiPublicRefreshContentRouteImport } from './routes/api/public/refresh-content'
import { Route as FoodCollectionSlugRouteImport } from './routes/food.collection.$slug'
import { Route as FoodRestaurantSlugRouteImport } from './routes/food.restaurant.$slug'
import { Route as ForumsThreadThreadIdRouteImport } from './routes/forums/thread.$threadId'
import { Route as PropertyCampaignIndexRouteImport } from './routes/property.$campaign.index'
import { Route as PropertyCampaignSlugRouteImport } from './routes/property.$campaign.$slug'
import { Route as TemplesTempleSlugRouteImport } from './routes/temples.temple.$slug'
import { Route as ApiPublicHooksBackfillImagesRouteImport } from './routes/api/public/hooks/backfill-images'
import { Route as ApiPublicHooksCollectNewsRouteImport } from './routes/api/public/hooks/collect-news'
import { Route as ApiPublicHooksDedupeSweepRouteImport } from './routes/api/public/hooks/dedupe-sweep'
import { Route as ApiPublicHooksDirectoryIngestRouteImport } from './routes/api/public/hooks/directory-ingest'
import { Route as ApiPublicHooksHealthAuditRouteImport } from './routes/api/public/hooks/health-audit'
import { Route as ApiPublicHooksIndiaIngestRouteImport } from './routes/api/public/hooks/india-ingest'
import { Route as ApiPublicHooksIngestSourcesRouteImport } from './routes/api/public/hooks/ingest-sources'
import { Route as ApiPublicHooksPublishNewsRouteImport } from './routes/api/public/hooks/publish-news'
import { Route as ApiPublicHooksTempleCalendarRouteImport } from './routes/api/public/hooks/temple-calendar'
import { Route as ApiPublicHooksYelpRestaurantsRouteImport } from './routes/api/public/hooks/yelp-restaurants'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsRoute = AssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BayAreaIconsRoute = BayAreaIconsRouteImport.update({
  id: '/bay-area-icons',
  path: '/bay-area-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CredaiHyderabad2026Route = CredaiHyderabad2026RouteImport.update({
  id: '/credai-hyderabad-2026',
  path: '/credai-hyderabad-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const CredaiShowRoute = CredaiShowRouteImport.update({
  id: '/credai-show',
  path: '/credai-show',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIngestRoute = DirectoryIngestRouteImport.update({
  id: '/directory-ingest',
  path: '/directory-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const EpaperRoute = EpaperRouteImport.update({
  id: '/epaper',
  path: '/epaper',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIngestRoute = FoodIngestRouteImport.update({
  id: '/food-ingest',
  path: '/food-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodMergeRoute = FoodMergeRouteImport.update({
  id: '/food-merge',
  path: '/food-merge',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationIconsRoute = FoundationIconsRouteImport.update({
  id: '/foundation-icons',
  path: '/foundation-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const GlamourDashboardRoute = GlamourDashboardRouteImport.update({
  id: '/glamour-dashboard',
  path: '/glamour-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteRoute = LiteRouteImport.update({
  id: '/lite',
  path: '/lite',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalDirectoryRoute = LocalDirectoryRouteImport.update({
  id: '/local-directory',
  path: '/local-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxedeskRoute = LuxedeskRouteImport.update({
  id: '/luxedesk',
  path: '/luxedesk',
  getParentRoute: () => rootRouteImport,
} as any)
const NriRealEstateRoute = NriRealEstateRouteImport.update({
  id: '/nri-real-estate',
  path: '/nri-real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyDeskRoute = PropertyDeskRouteImport.update({
  id: '/property-desk',
  path: '/property-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyVideosRoute = PropertyVideosRouteImport.update({
  id: '/property-videos',
  path: '/property-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDirectoryDotxmlRoute = SitemapDirectoryDotxmlRouteImport.update({
  id: '/sitemap-directory.xml',
  path: '/sitemap-directory.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapNewsDotxmlRoute = SitemapNewsDotxmlRouteImport.update({
  id: '/sitemap-news.xml',
  path: '/sitemap-news.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleSourcesRoute = TempleSourcesRouteImport.update({
  id: '/temple-sources',
  path: '/temple-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesRoute = TemplesRouteImport.update({
  id: '/temples',
  path: '/temples',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityRoute = CityCityRouteImport.update({
  id: '/city/$city',
  path: '/city/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorySlugRoute = DirectorySlugRouteImport.update({
  id: '/directory/$slug',
  path: '/directory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsTempleCalendarRoute = EventsTempleCalendarRouteImport.update({
  id: '/temple-calendar',
  path: '/temple-calendar',
  getParentRoute: () => EventsRoute,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoodRoute,
} as any)
const FoodAddRoute = FoodAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => FoodRoute,
} as any)
const FoodDealsRoute = FoodDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => FoodRoute,
} as any)
const FoodRestaurantsRoute = FoodRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => FoodRoute,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIndexRoute = PropertyIndexRouteImport.update({
  id: '/property/',
  path: '/property/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyCampaignRoute = PropertyCampaignRouteImport.update({
  id: '/property/$campaign',
  path: '/property/$campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesIndexRoute = TemplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplesRoute,
} as any)
const TemplesCityRoute = TemplesCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => TemplesRoute,
} as any)
const TemplesCalendarRoute = TemplesCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TemplesRoute,
} as any)
const TemplesNewsRoute = TemplesNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => TemplesRoute,
} as any)
const AuthenticatedAdminDriveImportRoute =
  AuthenticatedAdminDriveImportRouteImport.update({
    id: '/drive-import',
    path: '/drive-import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDuplicatesRoute =
  AuthenticatedAdminDuplicatesRouteImport.update({
    id: '/duplicates',
    path: '/duplicates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicRefreshContentRoute = ApiPublicRefreshContentRouteImport.update({
  id: '/api/public/refresh-content',
  path: '/api/public/refresh-content',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodCollectionSlugRoute = FoodCollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => FoodRoute,
} as any)
const FoodRestaurantSlugRoute = FoodRestaurantSlugRouteImport.update({
  id: '/restaurant/$slug',
  path: '/restaurant/$slug',
  getParentRoute: () => FoodRoute,
} as any)
const ForumsThreadThreadIdRoute = ForumsThreadThreadIdRouteImport.update({
  id: '/forums/thread/$threadId',
  path: '/forums/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyCampaignIndexRoute = PropertyCampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertyCampaignRoute,
} as any)
const PropertyCampaignSlugRoute = PropertyCampaignSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertyCampaignRoute,
} as any)
const TemplesTempleSlugRoute = TemplesTempleSlugRouteImport.update({
  id: '/temple/$slug',
  path: '/temple/$slug',
  getParentRoute: () => TemplesRoute,
} as any)
const ApiPublicHooksBackfillImagesRoute =
  ApiPublicHooksBackfillImagesRouteImport.update({
    id: '/api/public/hooks/backfill-images',
    path: '/api/public/hooks/backfill-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCollectNewsRoute =
  ApiPublicHooksCollectNewsRouteImport.update({
    id: '/api/public/hooks/collect-news',
    path: '/api/public/hooks/collect-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDedupeSweepRoute =
  ApiPublicHooksDedupeSweepRouteImport.update({
    id: '/api/public/hooks/dedupe-sweep',
    path: '/api/public/hooks/dedupe-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDirectoryIngestRoute =
  ApiPublicHooksDirectoryIngestRouteImport.update({
    id: '/api/public/hooks/directory-ingest',
    path: '/api/public/hooks/directory-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthAuditRoute =
  ApiPublicHooksHealthAuditRouteImport.update({
    id: '/api/public/hooks/health-audit',
    path: '/api/public/hooks/health-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIndiaIngestRoute =
  ApiPublicHooksIndiaIngestRouteImport.update({
    id: '/api/public/hooks/india-ingest',
    path: '/api/public/hooks/india-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestSourcesRoute =
  ApiPublicHooksIngestSourcesRouteImport.update({
    id: '/api/public/hooks/ingest-sources',
    path: '/api/public/hooks/ingest-sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishNewsRoute =
  ApiPublicHooksPublishNewsRouteImport.update({
    id: '/api/public/hooks/publish-news',
    path: '/api/public/hooks/publish-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTempleCalendarRoute =
  ApiPublicHooksTempleCalendarRouteImport.update({
    id: '/api/public/hooks/temple-calendar',
    path: '/api/public/hooks/temple-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksYelpRestaurantsRoute =
  ApiPublicHooksYelpRestaurantsRouteImport.update({
    id: '/api/public/hooks/yelp-restaurants',
    path: '/api/public/hooks/yelp-restaurants',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/associations': typeof AssociationsRoute
  '/auth': typeof AuthRoute
  '/bay-area-icons': typeof BayAreaIconsRoute
  '/command-center': typeof CommandCenterRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/credai-hyderabad-2026': typeof CredaiHyderabad2026Route
  '/credai-show': typeof CredaiShowRoute
  '/desk': typeof DeskRoute
  '/directory-ingest': typeof DirectoryIngestRoute
  '/epaper': typeof EpaperRoute
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/food': typeof FoodRouteWithChildren
  '/food-ingest': typeof FoodIngestRoute
  '/food-merge': typeof FoodMergeRoute
  '/foundation-icons': typeof FoundationIconsRoute
  '/glamour-dashboard': typeof GlamourDashboardRoute
  '/lite': typeof LiteRoute
  '/local-directory': typeof LocalDirectoryRoute
  '/luxedesk': typeof LuxedeskRoute
  '/nri-real-estate': typeof NriRealEstateRoute
  '/people': typeof PeopleRoute
  '/politics': typeof PoliticsRoute
  '/property-desk': typeof PropertyDeskRoute
  '/property-videos': typeof PropertyVideosRoute
  '/search': typeof SearchRoute
  '/sitemap-directory.xml': typeof SitemapDirectoryDotxmlRoute
  '/sitemap-news.xml': typeof SitemapNewsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/temple-sources': typeof TempleSourcesRoute
  '/temples': typeof TemplesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/health': typeof AuthenticatedHealthRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/city/$city': typeof CityCityRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/events/temple-calendar': typeof EventsTempleCalendarRoute
  '/food/add': typeof FoodAddRoute
  '/food/deals': typeof FoodDealsRoute
  '/food/restaurants': typeof FoodRestaurantsRoute
  '/property/$campaign': typeof PropertyCampaignRouteWithChildren
  '/temples/$city': typeof TemplesCityRoute
  '/temples/calendar': typeof TemplesCalendarRoute
  '/temples/news': typeof TemplesNewsRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/food/': typeof FoodIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/property/': typeof PropertyIndexRoute
  '/temples/': typeof TemplesIndexRoute
  '/admin/drive-import': typeof AuthenticatedAdminDriveImportRoute
  '/admin/duplicates': typeof AuthenticatedAdminDuplicatesRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/api/public/refresh-content': typeof ApiPublicRefreshContentRoute
  '/food/collection/$slug': typeof FoodCollectionSlugRoute
  '/food/restaurant/$slug': typeof FoodRestaurantSlugRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/property/$campaign/$slug': typeof PropertyCampaignSlugRoute
  '/temples/temple/$slug': typeof TemplesTempleSlugRoute
  '/property/$campaign/': typeof PropertyCampaignIndexRoute
  '/api/public/hooks/backfill-images': typeof ApiPublicHooksBackfillImagesRoute
  '/api/public/hooks/collect-news': typeof ApiPublicHooksCollectNewsRoute
  '/api/public/hooks/dedupe-sweep': typeof ApiPublicHooksDedupeSweepRoute
  '/api/public/hooks/directory-ingest': typeof ApiPublicHooksDirectoryIngestRoute
  '/api/public/hooks/health-audit': typeof ApiPublicHooksHealthAuditRoute
  '/api/public/hooks/india-ingest': typeof ApiPublicHooksIndiaIngestRoute
  '/api/public/hooks/ingest-sources': typeof ApiPublicHooksIngestSourcesRoute
  '/api/public/hooks/publish-news': typeof ApiPublicHooksPublishNewsRoute
  '/api/public/hooks/temple-calendar': typeof ApiPublicHooksTempleCalendarRoute
  '/api/public/hooks/yelp-restaurants': typeof ApiPublicHooksYelpRestaurantsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/associations': typeof AssociationsRoute
  '/auth': typeof AuthRoute
  '/bay-area-icons': typeof BayAreaIconsRoute
  '/command-center': typeof CommandCenterRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/credai-hyderabad-2026': typeof CredaiHyderabad2026Route
  '/credai-show': typeof CredaiShowRoute
  '/desk': typeof DeskRoute
  '/directory-ingest': typeof DirectoryIngestRoute
  '/epaper': typeof EpaperRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/food-ingest': typeof FoodIngestRoute
  '/food-merge': typeof FoodMergeRoute
  '/foundation-icons': typeof FoundationIconsRoute
  '/glamour-dashboard': typeof GlamourDashboardRoute
  '/lite': typeof LiteRoute
  '/local-directory': typeof LocalDirectoryRoute
  '/luxedesk': typeof LuxedeskRoute
  '/nri-real-estate': typeof NriRealEstateRoute
  '/people': typeof PeopleRoute
  '/politics': typeof PoliticsRoute
  '/property-desk': typeof PropertyDeskRoute
  '/property-videos': typeof PropertyVideosRoute
  '/search': typeof SearchRoute
  '/sitemap-directory.xml': typeof SitemapDirectoryDotxmlRoute
  '/sitemap-news.xml': typeof SitemapNewsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/temple-sources': typeof TempleSourcesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/health': typeof AuthenticatedHealthRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/city/$city': typeof CityCityRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/events/temple-calendar': typeof EventsTempleCalendarRoute
  '/food/add': typeof FoodAddRoute
  '/food/deals': typeof FoodDealsRoute
  '/food/restaurants': typeof FoodRestaurantsRoute
  '/temples/$city': typeof TemplesCityRoute
  '/temples/calendar': typeof TemplesCalendarRoute
  '/temples/news': typeof TemplesNewsRoute
  '/directory': typeof DirectoryIndexRoute
  '/events': typeof EventsIndexRoute
  '/food': typeof FoodIndexRoute
  '/forums': typeof ForumsIndexRoute
  '/property': typeof PropertyIndexRoute
  '/temples': typeof TemplesIndexRoute
  '/admin/drive-import': typeof AuthenticatedAdminDriveImportRoute
  '/admin/duplicates': typeof AuthenticatedAdminDuplicatesRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/api/public/refresh-content': typeof ApiPublicRefreshContentRoute
  '/food/collection/$slug': typeof FoodCollectionSlugRoute
  '/food/restaurant/$slug': typeof FoodRestaurantSlugRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/property/$campaign/$slug': typeof PropertyCampaignSlugRoute
  '/temples/temple/$slug': typeof TemplesTempleSlugRoute
  '/property/$campaign': typeof PropertyCampaignIndexRoute
  '/api/public/hooks/backfill-images': typeof ApiPublicHooksBackfillImagesRoute
  '/api/public/hooks/collect-news': typeof ApiPublicHooksCollectNewsRoute
  '/api/public/hooks/dedupe-sweep': typeof ApiPublicHooksDedupeSweepRoute
  '/api/public/hooks/directory-ingest': typeof ApiPublicHooksDirectoryIngestRoute
  '/api/public/hooks/health-audit': typeof ApiPublicHooksHealthAuditRoute
  '/api/public/hooks/india-ingest': typeof ApiPublicHooksIndiaIngestRoute
  '/api/public/hooks/ingest-sources': typeof ApiPublicHooksIngestSourcesRoute
  '/api/public/hooks/publish-news': typeof ApiPublicHooksPublishNewsRoute
  '/api/public/hooks/temple-calendar': typeof ApiPublicHooksTempleCalendarRoute
  '/api/public/hooks/yelp-restaurants': typeof ApiPublicHooksYelpRestaurantsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/associations': typeof AssociationsRoute
  '/auth': typeof AuthRoute
  '/bay-area-icons': typeof BayAreaIconsRoute
  '/command-center': typeof CommandCenterRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/credai-hyderabad-2026': typeof CredaiHyderabad2026Route
  '/credai-show': typeof CredaiShowRoute
  '/desk': typeof DeskRoute
  '/directory-ingest': typeof DirectoryIngestRoute
  '/epaper': typeof EpaperRoute
  '/events': typeof EventsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/food': typeof FoodRouteWithChildren
  '/food-ingest': typeof FoodIngestRoute
  '/food-merge': typeof FoodMergeRoute
  '/foundation-icons': typeof FoundationIconsRoute
  '/glamour-dashboard': typeof GlamourDashboardRoute
  '/lite': typeof LiteRoute
  '/local-directory': typeof LocalDirectoryRoute
  '/luxedesk': typeof LuxedeskRoute
  '/nri-real-estate': typeof NriRealEstateRoute
  '/people': typeof PeopleRoute
  '/politics': typeof PoliticsRoute
  '/property-desk': typeof PropertyDeskRoute
  '/property-videos': typeof PropertyVideosRoute
  '/search': typeof SearchRoute
  '/sitemap-directory.xml': typeof SitemapDirectoryDotxmlRoute
  '/sitemap-news.xml': typeof SitemapNewsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/temple-sources': typeof TempleSourcesRoute
  '/temples': typeof TemplesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/city/$city': typeof CityCityRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/events/temple-calendar': typeof EventsTempleCalendarRoute
  '/food/add': typeof FoodAddRoute
  '/food/deals': typeof FoodDealsRoute
  '/food/restaurants': typeof FoodRestaurantsRoute
  '/property/$campaign': typeof PropertyCampaignRouteWithChildren
  '/temples/$city': typeof TemplesCityRoute
  '/temples/calendar': typeof TemplesCalendarRoute
  '/temples/news': typeof TemplesNewsRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/food/': typeof FoodIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/property/': typeof PropertyIndexRoute
  '/temples/': typeof TemplesIndexRoute
  '/_authenticated/admin/drive-import': typeof AuthenticatedAdminDriveImportRoute
  '/_authenticated/admin/duplicates': typeof AuthenticatedAdminDuplicatesRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/api/public/refresh-content': typeof ApiPublicRefreshContentRoute
  '/food/collection/$slug': typeof FoodCollectionSlugRoute
  '/food/restaurant/$slug': typeof FoodRestaurantSlugRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/property/$campaign/$slug': typeof PropertyCampaignSlugRoute
  '/temples/temple/$slug': typeof TemplesTempleSlugRoute
  '/property/$campaign/': typeof PropertyCampaignIndexRoute
  '/api/public/hooks/backfill-images': typeof ApiPublicHooksBackfillImagesRoute
  '/api/public/hooks/collect-news': typeof ApiPublicHooksCollectNewsRoute
  '/api/public/hooks/dedupe-sweep': typeof ApiPublicHooksDedupeSweepRoute
  '/api/public/hooks/directory-ingest': typeof ApiPublicHooksDirectoryIngestRoute
  '/api/public/hooks/health-audit': typeof ApiPublicHooksHealthAuditRoute
  '/api/public/hooks/india-ingest': typeof ApiPublicHooksIndiaIngestRoute
  '/api/public/hooks/ingest-sources': typeof ApiPublicHooksIngestSourcesRoute
  '/api/public/hooks/publish-news': typeof ApiPublicHooksPublishNewsRoute
  '/api/public/hooks/temple-calendar': typeof ApiPublicHooksTempleCalendarRoute
  '/api/public/hooks/yelp-restaurants': typeof ApiPublicHooksYelpRestaurantsRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/associations'
    | '/auth'
    | '/bay-area-icons'
    | '/command-center'
    | '/connect'
    | '/contact'
    | '/credai-hyderabad-2026'
    | '/credai-show'
    | '/desk'
    | '/directory-ingest'
    | '/epaper'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/food'
    | '/food-ingest'
    | '/food-merge'
    | '/foundation-icons'
    | '/glamour-dashboard'
    | '/lite'
    | '/local-directory'
    | '/luxedesk'
    | '/nri-real-estate'
    | '/people'
    | '/politics'
    | '/property-desk'
    | '/property-videos'
    | '/search'
    | '/sitemap-directory.xml'
    | '/sitemap-news.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/temple-sources'
    | '/temples'
    | '/admin'
    | '/health'
    | '/article/$slug'
    | '/category/$category'
    | '/city/$city'
    | '/directory/$slug'
    | '/events/temple-calendar'
    | '/food/add'
    | '/food/deals'
    | '/food/restaurants'
    | '/property/$campaign'
    | '/temples/$city'
    | '/temples/calendar'
    | '/temples/news'
    | '/directory/'
    | '/events/'
    | '/food/'
    | '/forums/'
    | '/property/'
    | '/temples/'
    | '/admin/drive-import'
    | '/admin/duplicates'
    | '/admin/health'
    | '/api/public/refresh-content'
    | '/food/collection/$slug'
    | '/food/restaurant/$slug'
    | '/forums/thread/$threadId'
    | '/property/$campaign/$slug'
    | '/temples/temple/$slug'
    | '/property/$campaign/'
    | '/api/public/hooks/backfill-images'
    | '/api/public/hooks/collect-news'
    | '/api/public/hooks/dedupe-sweep'
    | '/api/public/hooks/directory-ingest'
    | '/api/public/hooks/health-audit'
    | '/api/public/hooks/india-ingest'
    | '/api/public/hooks/ingest-sources'
    | '/api/public/hooks/publish-news'
    | '/api/public/hooks/temple-calendar'
    | '/api/public/hooks/yelp-restaurants'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/associations'
    | '/auth'
    | '/bay-area-icons'
    | '/command-center'
    | '/connect'
    | '/contact'
    | '/credai-hyderabad-2026'
    | '/credai-show'
    | '/desk'
    | '/directory-ingest'
    | '/epaper'
    | '/explore'
    | '/favorites'
    | '/food-ingest'
    | '/food-merge'
    | '/foundation-icons'
    | '/glamour-dashboard'
    | '/lite'
    | '/local-directory'
    | '/luxedesk'
    | '/nri-real-estate'
    | '/people'
    | '/politics'
    | '/property-desk'
    | '/property-videos'
    | '/search'
    | '/sitemap-directory.xml'
    | '/sitemap-news.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/temple-sources'
    | '/admin'
    | '/health'
    | '/article/$slug'
    | '/category/$category'
    | '/city/$city'
    | '/directory/$slug'
    | '/events/temple-calendar'
    | '/food/add'
    | '/food/deals'
    | '/food/restaurants'
    | '/temples/$city'
    | '/temples/calendar'
    | '/temples/news'
    | '/directory'
    | '/events'
    | '/food'
    | '/forums'
    | '/property'
    | '/temples'
    | '/admin/drive-import'
    | '/admin/duplicates'
    | '/admin/health'
    | '/api/public/refresh-content'
    | '/food/collection/$slug'
    | '/food/restaurant/$slug'
    | '/forums/thread/$threadId'
    | '/property/$campaign/$slug'
    | '/temples/temple/$slug'
    | '/property/$campaign'
    | '/api/public/hooks/backfill-images'
    | '/api/public/hooks/collect-news'
    | '/api/public/hooks/dedupe-sweep'
    | '/api/public/hooks/directory-ingest'
    | '/api/public/hooks/health-audit'
    | '/api/public/hooks/india-ingest'
    | '/api/public/hooks/ingest-sources'
    | '/api/public/hooks/publish-news'
    | '/api/public/hooks/temple-calendar'
    | '/api/public/hooks/yelp-restaurants'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/associations'
    | '/auth'
    | '/bay-area-icons'
    | '/command-center'
    | '/connect'
    | '/contact'
    | '/credai-hyderabad-2026'
    | '/credai-show'
    | '/desk'
    | '/directory-ingest'
    | '/epaper'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/food'
    | '/food-ingest'
    | '/food-merge'
    | '/foundation-icons'
    | '/glamour-dashboard'
    | '/lite'
    | '/local-directory'
    | '/luxedesk'
    | '/nri-real-estate'
    | '/people'
    | '/politics'
    | '/property-desk'
    | '/property-videos'
    | '/search'
    | '/sitemap-directory.xml'
    | '/sitemap-news.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/temple-sources'
    | '/temples'
    | '/_authenticated/admin'
    | '/_authenticated/health'
    | '/article/$slug'
    | '/category/$category'
    | '/city/$city'
    | '/directory/$slug'
    | '/events/temple-calendar'
    | '/food/add'
    | '/food/deals'
    | '/food/restaurants'
    | '/property/$campaign'
    | '/temples/$city'
    | '/temples/calendar'
    | '/temples/news'
    | '/directory/'
    | '/events/'
    | '/food/'
    | '/forums/'
    | '/property/'
    | '/temples/'
    | '/_authenticated/admin/drive-import'
    | '/_authenticated/admin/duplicates'
    | '/_authenticated/admin/health'
    | '/api/public/refresh-content'
    | '/food/collection/$slug'
    | '/food/restaurant/$slug'
    | '/forums/thread/$threadId'
    | '/property/$campaign/$slug'
    | '/temples/temple/$slug'
    | '/property/$campaign/'
    | '/api/public/hooks/backfill-images'
    | '/api/public/hooks/collect-news'
    | '/api/public/hooks/dedupe-sweep'
    | '/api/public/hooks/directory-ingest'
    | '/api/public/hooks/health-audit'
    | '/api/public/hooks/india-ingest'
    | '/api/public/hooks/ingest-sources'
    | '/api/public/hooks/publish-news'
    | '/api/public/hooks/temple-calendar'
    | '/api/public/hooks/yelp-restaurants'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssociationsRoute: typeof AssociationsRoute
  AuthRoute: typeof AuthRoute
  BayAreaIconsRoute: typeof BayAreaIconsRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  CredaiHyderabad2026Route: typeof CredaiHyderabad2026Route
  CredaiShowRoute: typeof CredaiShowRoute
  DeskRoute: typeof DeskRoute
  DirectoryIngestRoute: typeof DirectoryIngestRoute
  EpaperRoute: typeof EpaperRoute
  EventsRoute: typeof EventsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  FoodRoute: typeof FoodRouteWithChildren
  FoodIngestRoute: typeof FoodIngestRoute
  FoodMergeRoute: typeof FoodMergeRoute
  FoundationIconsRoute: typeof FoundationIconsRoute
  GlamourDashboardRoute: typeof GlamourDashboardRoute
  LiteRoute: typeof LiteRoute
  LocalDirectoryRoute: typeof LocalDirectoryRoute
  LuxedeskRoute: typeof LuxedeskRoute
  NriRealEstateRoute: typeof NriRealEstateRoute
  PeopleRoute: typeof PeopleRoute
  PoliticsRoute: typeof PoliticsRoute
  PropertyDeskRoute: typeof PropertyDeskRoute
  PropertyVideosRoute: typeof PropertyVideosRoute
  SearchRoute: typeof SearchRoute
  SitemapDirectoryDotxmlRoute: typeof SitemapDirectoryDotxmlRoute
  SitemapNewsDotxmlRoute: typeof SitemapNewsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  TempleSourcesRoute: typeof TempleSourcesRoute
  TemplesRoute: typeof TemplesRouteWithChildren
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  CityCityRoute: typeof CityCityRoute
  DirectorySlugRoute: typeof DirectorySlugRoute
  PropertyCampaignRoute: typeof PropertyCampaignRouteWithChildren
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  PropertyIndexRoute: typeof PropertyIndexRoute
  ApiPublicRefreshContentRoute: typeof ApiPublicRefreshContentRoute
  ForumsThreadThreadIdRoute: typeof ForumsThreadThreadIdRoute
  ApiPublicHooksBackfillImagesRoute: typeof ApiPublicHooksBackfillImagesRoute
  ApiPublicHooksCollectNewsRoute: typeof ApiPublicHooksCollectNewsRoute
  ApiPublicHooksDedupeSweepRoute: typeof ApiPublicHooksDedupeSweepRoute
  ApiPublicHooksDirectoryIngestRoute: typeof ApiPublicHooksDirectoryIngestRoute
  ApiPublicHooksHealthAuditRoute: typeof ApiPublicHooksHealthAuditRoute
  ApiPublicHooksIndiaIngestRoute: typeof ApiPublicHooksIndiaIngestRoute
  ApiPublicHooksIngestSourcesRoute: typeof ApiPublicHooksIngestSourcesRoute
  ApiPublicHooksPublishNewsRoute: typeof ApiPublicHooksPublishNewsRoute
  ApiPublicHooksTempleCalendarRoute: typeof ApiPublicHooksTempleCalendarRoute
  ApiPublicHooksYelpRestaurantsRoute: typeof ApiPublicHooksYelpRestaurantsRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations': {
      id: '/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AssociationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bay-area-icons': {
      id: '/bay-area-icons'
      path: '/bay-area-icons'
      fullPath: '/bay-area-icons'
      preLoaderRoute: typeof BayAreaIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credai-hyderabad-2026': {
      id: '/credai-hyderabad-2026'
      path: '/credai-hyderabad-2026'
      fullPath: '/credai-hyderabad-2026'
      preLoaderRoute: typeof CredaiHyderabad2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credai-show': {
      id: '/credai-show'
      path: '/credai-show'
      fullPath: '/credai-show'
      preLoaderRoute: typeof CredaiShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory-ingest': {
      id: '/directory-ingest'
      path: '/directory-ingest'
      fullPath: '/directory-ingest'
      preLoaderRoute: typeof DirectoryIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epaper': {
      id: '/epaper'
      path: '/epaper'
      fullPath: '/epaper'
      preLoaderRoute: typeof EpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-ingest': {
      id: '/food-ingest'
      path: '/food-ingest'
      fullPath: '/food-ingest'
      preLoaderRoute: typeof FoodIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-merge': {
      id: '/food-merge'
      path: '/food-merge'
      fullPath: '/food-merge'
      preLoaderRoute: typeof FoodMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation-icons': {
      id: '/foundation-icons'
      path: '/foundation-icons'
      fullPath: '/foundation-icons'
      preLoaderRoute: typeof FoundationIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glamour-dashboard': {
      id: '/glamour-dashboard'
      path: '/glamour-dashboard'
      fullPath: '/glamour-dashboard'
      preLoaderRoute: typeof GlamourDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite': {
      id: '/lite'
      path: '/lite'
      fullPath: '/lite'
      preLoaderRoute: typeof LiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-directory': {
      id: '/local-directory'
      path: '/local-directory'
      fullPath: '/local-directory'
      preLoaderRoute: typeof LocalDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxedesk': {
      id: '/luxedesk'
      path: '/luxedesk'
      fullPath: '/luxedesk'
      preLoaderRoute: typeof LuxedeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nri-real-estate': {
      id: '/nri-real-estate'
      path: '/nri-real-estate'
      fullPath: '/nri-real-estate'
      preLoaderRoute: typeof NriRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-desk': {
      id: '/property-desk'
      path: '/property-desk'
      fullPath: '/property-desk'
      preLoaderRoute: typeof PropertyDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-videos': {
      id: '/property-videos'
      path: '/property-videos'
      fullPath: '/property-videos'
      preLoaderRoute: typeof PropertyVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-directory.xml': {
      id: '/sitemap-directory.xml'
      path: '/sitemap-directory.xml'
      fullPath: '/sitemap-directory.xml'
      preLoaderRoute: typeof SitemapDirectoryDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-news.xml': {
      id: '/sitemap-news.xml'
      path: '/sitemap-news.xml'
      fullPath: '/sitemap-news.xml'
      preLoaderRoute: typeof SitemapNewsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple-sources': {
      id: '/temple-sources'
      path: '/temple-sources'
      fullPath: '/temple-sources'
      preLoaderRoute: typeof TempleSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples': {
      id: '/temples'
      path: '/temples'
      fullPath: '/temples'
      preLoaderRoute: typeof TemplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$city': {
      id: '/city/$city'
      path: '/city/$city'
      fullPath: '/city/$city'
      preLoaderRoute: typeof CityCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$slug': {
      id: '/directory/$slug'
      path: '/directory/$slug'
      fullPath: '/directory/$slug'
      preLoaderRoute: typeof DirectorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/temple-calendar': {
      id: '/events/temple-calendar'
      path: '/temple-calendar'
      fullPath: '/events/temple-calendar'
      preLoaderRoute: typeof EventsTempleCalendarRouteImport
      parentRoute: typeof EventsRoute
    }
    '/food/': {
      id: '/food/'
      path: '/'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/add': {
      id: '/food/add'
      path: '/add'
      fullPath: '/food/add'
      preLoaderRoute: typeof FoodAddRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/deals': {
      id: '/food/deals'
      path: '/deals'
      fullPath: '/food/deals'
      preLoaderRoute: typeof FoodDealsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/restaurants': {
      id: '/food/restaurants'
      path: '/restaurants'
      fullPath: '/food/restaurants'
      preLoaderRoute: typeof FoodRestaurantsRouteImport
      parentRoute: typeof FoodRoute
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/': {
      id: '/property/'
      path: '/property'
      fullPath: '/property/'
      preLoaderRoute: typeof PropertyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$campaign': {
      id: '/property/$campaign'
      path: '/property/$campaign'
      fullPath: '/property/$campaign'
      preLoaderRoute: typeof PropertyCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/': {
      id: '/temples/'
      path: '/'
      fullPath: '/temples/'
      preLoaderRoute: typeof TemplesIndexRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/temples/$city': {
      id: '/temples/$city'
      path: '/$city'
      fullPath: '/temples/$city'
      preLoaderRoute: typeof TemplesCityRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/temples/calendar': {
      id: '/temples/calendar'
      path: '/calendar'
      fullPath: '/temples/calendar'
      preLoaderRoute: typeof TemplesCalendarRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/temples/news': {
      id: '/temples/news'
      path: '/news'
      fullPath: '/temples/news'
      preLoaderRoute: typeof TemplesNewsRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/_authenticated/admin/drive-import': {
      id: '/_authenticated/admin/drive-import'
      path: '/drive-import'
      fullPath: '/admin/drive-import'
      preLoaderRoute: typeof AuthenticatedAdminDriveImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/duplicates': {
      id: '/_authenticated/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AuthenticatedAdminDuplicatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/refresh-content': {
      id: '/api/public/refresh-content'
      path: '/api/public/refresh-content'
      fullPath: '/api/public/refresh-content'
      preLoaderRoute: typeof ApiPublicRefreshContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/collection/$slug': {
      id: '/food/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/food/collection/$slug'
      preLoaderRoute: typeof FoodCollectionSlugRouteImport
      parentRoute: typeof FoodRoute
    }
    '/food/restaurant/$slug': {
      id: '/food/restaurant/$slug'
      path: '/restaurant/$slug'
      fullPath: '/food/restaurant/$slug'
      preLoaderRoute: typeof FoodRestaurantSlugRouteImport
      parentRoute: typeof FoodRoute
    }
    '/forums/thread/$threadId': {
      id: '/forums/thread/$threadId'
      path: '/forums/thread/$threadId'
      fullPath: '/forums/thread/$threadId'
      preLoaderRoute: typeof ForumsThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$campaign/': {
      id: '/property/$campaign/'
      path: '/'
      fullPath: '/property/$campaign/'
      preLoaderRoute: typeof PropertyCampaignIndexRouteImport
      parentRoute: typeof PropertyCampaignRoute
    }
    '/property/$campaign/$slug': {
      id: '/property/$campaign/$slug'
      path: '/$slug'
      fullPath: '/property/$campaign/$slug'
      preLoaderRoute: typeof PropertyCampaignSlugRouteImport
      parentRoute: typeof PropertyCampaignRoute
    }
    '/temples/temple/$slug': {
      id: '/temples/temple/$slug'
      path: '/temple/$slug'
      fullPath: '/temples/temple/$slug'
      preLoaderRoute: typeof TemplesTempleSlugRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/api/public/hooks/backfill-images': {
      id: '/api/public/hooks/backfill-images'
      path: '/api/public/hooks/backfill-images'
      fullPath: '/api/public/hooks/backfill-images'
      preLoaderRoute: typeof ApiPublicHooksBackfillImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/collect-news': {
      id: '/api/public/hooks/collect-news'
      path: '/api/public/hooks/collect-news'
      fullPath: '/api/public/hooks/collect-news'
      preLoaderRoute: typeof ApiPublicHooksCollectNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dedupe-sweep': {
      id: '/api/public/hooks/dedupe-sweep'
      path: '/api/public/hooks/dedupe-sweep'
      fullPath: '/api/public/hooks/dedupe-sweep'
      preLoaderRoute: typeof ApiPublicHooksDedupeSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/directory-ingest': {
      id: '/api/public/hooks/directory-ingest'
      path: '/api/public/hooks/directory-ingest'
      fullPath: '/api/public/hooks/directory-ingest'
      preLoaderRoute: typeof ApiPublicHooksDirectoryIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-audit': {
      id: '/api/public/hooks/health-audit'
      path: '/api/public/hooks/health-audit'
      fullPath: '/api/public/hooks/health-audit'
      preLoaderRoute: typeof ApiPublicHooksHealthAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/india-ingest': {
      id: '/api/public/hooks/india-ingest'
      path: '/api/public/hooks/india-ingest'
      fullPath: '/api/public/hooks/india-ingest'
      preLoaderRoute: typeof ApiPublicHooksIndiaIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-sources': {
      id: '/api/public/hooks/ingest-sources'
      path: '/api/public/hooks/ingest-sources'
      fullPath: '/api/public/hooks/ingest-sources'
      preLoaderRoute: typeof ApiPublicHooksIngestSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-news': {
      id: '/api/public/hooks/publish-news'
      path: '/api/public/hooks/publish-news'
      fullPath: '/api/public/hooks/publish-news'
      preLoaderRoute: typeof ApiPublicHooksPublishNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/temple-calendar': {
      id: '/api/public/hooks/temple-calendar'
      path: '/api/public/hooks/temple-calendar'
      fullPath: '/api/public/hooks/temple-calendar'
      preLoaderRoute: typeof ApiPublicHooksTempleCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/yelp-restaurants': {
      id: '/api/public/hooks/yelp-restaurants'
      path: '/api/public/hooks/yelp-restaurants'
      fullPath: '/api/public/hooks/yelp-restaurants'
      preLoaderRoute: typeof ApiPublicHooksYelpRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDriveImportRoute: typeof AuthenticatedAdminDriveImportRoute
  AuthenticatedAdminDuplicatesRoute: typeof AuthenticatedAdminDuplicatesRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDriveImportRoute: AuthenticatedAdminDriveImportRoute,
  AuthenticatedAdminDuplicatesRoute: AuthenticatedAdminDuplicatesRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventsRouteChildren {
  EventsTempleCalendarRoute: typeof EventsTempleCalendarRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsTempleCalendarRoute: EventsTempleCalendarRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface FoodRouteChildren {
  FoodAddRoute: typeof FoodAddRoute
  FoodDealsRoute: typeof FoodDealsRoute
  FoodRestaurantsRoute: typeof FoodRestaurantsRoute
  FoodIndexRoute: typeof FoodIndexRoute
  FoodCollectionSlugRoute: typeof FoodCollectionSlugRoute
  FoodRestaurantSlugRoute: typeof FoodRestaurantSlugRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodAddRoute: FoodAddRoute,
  FoodDealsRoute: FoodDealsRoute,
  FoodRestaurantsRoute: FoodRestaurantsRoute,
  FoodIndexRoute: FoodIndexRoute,
  FoodCollectionSlugRoute: FoodCollectionSlugRoute,
  FoodRestaurantSlugRoute: FoodRestaurantSlugRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

interface TemplesRouteChildren {
  TemplesCityRoute: typeof TemplesCityRoute
  TemplesCalendarRoute: typeof TemplesCalendarRoute
  TemplesNewsRoute: typeof TemplesNewsRoute
  TemplesIndexRoute: typeof TemplesIndexRoute
  TemplesTempleSlugRoute: typeof TemplesTempleSlugRoute
}

const TemplesRouteChildren: TemplesRouteChildren = {
  TemplesCityRoute: TemplesCityRoute,
  TemplesCalendarRoute: TemplesCalendarRoute,
  TemplesNewsRoute: TemplesNewsRoute,
  TemplesIndexRoute: TemplesIndexRoute,
  TemplesTempleSlugRoute: TemplesTempleSlugRoute,
}

const TemplesRouteWithChildren =
  TemplesRoute._addFileChildren(TemplesRouteChildren)

interface PropertyCampaignRouteChildren {
  PropertyCampaignSlugRoute: typeof PropertyCampaignSlugRoute
  PropertyCampaignIndexRoute: typeof PropertyCampaignIndexRoute
}

const PropertyCampaignRouteChildren: PropertyCampaignRouteChildren = {
  PropertyCampaignSlugRoute: PropertyCampaignSlugRoute,
  PropertyCampaignIndexRoute: PropertyCampaignIndexRoute,
}

const PropertyCampaignRouteWithChildren =
  PropertyCampaignRoute._addFileChildren(PropertyCampaignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssociationsRoute: AssociationsRoute,
  AuthRoute: AuthRoute,
  BayAreaIconsRoute: BayAreaIconsRoute,
  CommandCenterRoute: CommandCenterRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  CredaiHyderabad2026Route: CredaiHyderabad2026Route,
  CredaiShowRoute: CredaiShowRoute,
  DeskRoute: DeskRoute,
  DirectoryIngestRoute: DirectoryIngestRoute,
  EpaperRoute: EpaperRoute,
  EventsRoute: EventsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  FoodRoute: FoodRouteWithChildren,
  FoodIngestRoute: FoodIngestRoute,
  FoodMergeRoute: FoodMergeRoute,
  FoundationIconsRoute: FoundationIconsRoute,
  GlamourDashboardRoute: GlamourDashboardRoute,
  LiteRoute: LiteRoute,
  LocalDirectoryRoute: LocalDirectoryRoute,
  LuxedeskRoute: LuxedeskRoute,
  NriRealEstateRoute: NriRealEstateRoute,
  PeopleRoute: PeopleRoute,
  PoliticsRoute: PoliticsRoute,
  PropertyDeskRoute: PropertyDeskRoute,
  PropertyVideosRoute: PropertyVideosRoute,
  SearchRoute: SearchRoute,
  SitemapDirectoryDotxmlRoute: SitemapDirectoryDotxmlRoute,
  SitemapNewsDotxmlRoute: SitemapNewsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  TempleSourcesRoute: TempleSourcesRoute,
  TemplesRoute: TemplesRouteWithChildren,
  ArticleSlugRoute: ArticleSlugRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  CityCityRoute: CityCityRoute,
  DirectorySlugRoute: DirectorySlugRoute,
  PropertyCampaignRoute: PropertyCampaignRouteWithChildren,
  DirectoryIndexRoute: DirectoryIndexRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  PropertyIndexRoute: PropertyIndexRoute,
  ApiPublicRefreshContentRoute: ApiPublicRefreshContentRoute,
  ForumsThreadThreadIdRoute: ForumsThreadThreadIdRoute,
  ApiPublicHooksBackfillImagesRoute: ApiPublicHooksBackfillImagesRoute,
  ApiPublicHooksCollectNewsRoute: ApiPublicHooksCollectNewsRoute,
  ApiPublicHooksDedupeSweepRoute: ApiPublicHooksDedupeSweepRoute,
  ApiPublicHooksDirectoryIngestRoute: ApiPublicHooksDirectoryIngestRoute,
  ApiPublicHooksHealthAuditRoute: ApiPublicHooksHealthAuditRoute,
  ApiPublicHooksIndiaIngestRoute: ApiPublicHooksIndiaIngestRoute,
  ApiPublicHooksIngestSourcesRoute: ApiPublicHooksIngestSourcesRoute,
  ApiPublicHooksPublishNewsRoute: ApiPublicHooksPublishNewsRoute,
  ApiPublicHooksTempleCalendarRoute: ApiPublicHooksTempleCalendarRoute,
  ApiPublicHooksYelpRestaurantsRoute: ApiPublicHooksYelpRestaurantsRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
