/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssociationsRouteImport } from './routes/associations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BayAreaIconsRouteImport } from './routes/bay-area-icons'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as EpaperRouteImport } from './routes/epaper'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FoundationIconsRouteImport } from './routes/foundation-icons'
import { Route as LiteRouteImport } from './routes/lite'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TemplesRouteImport } from './routes/temples'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as CityCityRouteImport } from './routes/city.$city'
import { Route as ForumsIndexRouteImport } from './routes/forums/index'
import { Route as TemplesIndexRouteImport } from './routes/temples.index'
import { Route as TemplesCityRouteImport } from './routes/temples.$city'
import { Route as ApiPublicRefreshContentRouteImport } from './routes/api/public/refresh-content'
import { Route as ForumsThreadThreadIdRouteImport } from './routes/forums/thread.$threadId'
import { Route as TemplesTempleSlugRouteImport } from './routes/temples.temple.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsRoute = AssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BayAreaIconsRoute = BayAreaIconsRouteImport.update({
  id: '/bay-area-icons',
  path: '/bay-area-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const EpaperRoute = EpaperRouteImport.update({
  id: '/epaper',
  path: '/epaper',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationIconsRoute = FoundationIconsRouteImport.update({
  id: '/foundation-icons',
  path: '/foundation-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteRoute = LiteRouteImport.update({
  id: '/lite',
  path: '/lite',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesRoute = TemplesRouteImport.update({
  id: '/temples',
  path: '/temples',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityRoute = CityCityRouteImport.update({
  id: '/city/$city',
  path: '/city/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesIndexRoute = TemplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplesRoute,
} as any)
const TemplesCityRoute = TemplesCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => TemplesRoute,
} as any)
const ApiPublicRefreshContentRoute = ApiPublicRefreshContentRouteImport.update({
  id: '/api/public/refresh-content',
  path: '/api/public/refresh-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsThreadThreadIdRoute = ForumsThreadThreadIdRouteImport.update({
  id: '/forums/thread/$threadId',
  path: '/forums/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesTempleSlugRoute = TemplesTempleSlugRouteImport.update({
  id: '/temple/$slug',
  path: '/temple/$slug',
  getParentRoute: () => TemplesRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/associations': typeof AssociationsRoute
  '/auth': typeof AuthRoute
  '/bay-area-icons': typeof BayAreaIconsRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/epaper': typeof EpaperRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/foundation-icons': typeof FoundationIconsRoute
  '/lite': typeof LiteRoute
  '/people': typeof PeopleRoute
  '/politics': typeof PoliticsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/temples': typeof TemplesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/health': typeof AuthenticatedHealthRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/city/$city': typeof CityCityRoute
  '/temples/$city': typeof TemplesCityRoute
  '/forums/': typeof ForumsIndexRoute
  '/temples/': typeof TemplesIndexRoute
  '/api/public/refresh-content': typeof ApiPublicRefreshContentRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/temples/temple/$slug': typeof TemplesTempleSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/associations': typeof AssociationsRoute
  '/auth': typeof AuthRoute
  '/bay-area-icons': typeof BayAreaIconsRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/epaper': typeof EpaperRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/foundation-icons': typeof FoundationIconsRoute
  '/lite': typeof LiteRoute
  '/people': typeof PeopleRoute
  '/politics': typeof PoliticsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/health': typeof AuthenticatedHealthRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/city/$city': typeof CityCityRoute
  '/temples/$city': typeof TemplesCityRoute
  '/forums': typeof ForumsIndexRoute
  '/temples': typeof TemplesIndexRoute
  '/api/public/refresh-content': typeof ApiPublicRefreshContentRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/temples/temple/$slug': typeof TemplesTempleSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/associations': typeof AssociationsRoute
  '/auth': typeof AuthRoute
  '/bay-area-icons': typeof BayAreaIconsRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/epaper': typeof EpaperRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/foundation-icons': typeof FoundationIconsRoute
  '/lite': typeof LiteRoute
  '/people': typeof PeopleRoute
  '/politics': typeof PoliticsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/temples': typeof TemplesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/city/$city': typeof CityCityRoute
  '/temples/$city': typeof TemplesCityRoute
  '/forums/': typeof ForumsIndexRoute
  '/temples/': typeof TemplesIndexRoute
  '/api/public/refresh-content': typeof ApiPublicRefreshContentRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/temples/temple/$slug': typeof TemplesTempleSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/associations'
    | '/auth'
    | '/bay-area-icons'
    | '/connect'
    | '/contact'
    | '/directory'
    | '/epaper'
    | '/events'
    | '/explore'
    | '/foundation-icons'
    | '/lite'
    | '/people'
    | '/politics'
    | '/search'
    | '/sitemap.xml'
    | '/submit'
    | '/temples'
    | '/admin'
    | '/health'
    | '/article/$slug'
    | '/category/$category'
    | '/city/$city'
    | '/temples/$city'
    | '/forums/'
    | '/temples/'
    | '/api/public/refresh-content'
    | '/forums/thread/$threadId'
    | '/temples/temple/$slug'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/associations'
    | '/auth'
    | '/bay-area-icons'
    | '/connect'
    | '/contact'
    | '/directory'
    | '/epaper'
    | '/events'
    | '/explore'
    | '/foundation-icons'
    | '/lite'
    | '/people'
    | '/politics'
    | '/search'
    | '/sitemap.xml'
    | '/submit'
    | '/admin'
    | '/health'
    | '/article/$slug'
    | '/category/$category'
    | '/city/$city'
    | '/temples/$city'
    | '/forums'
    | '/temples'
    | '/api/public/refresh-content'
    | '/forums/thread/$threadId'
    | '/temples/temple/$slug'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/associations'
    | '/auth'
    | '/bay-area-icons'
    | '/connect'
    | '/contact'
    | '/directory'
    | '/epaper'
    | '/events'
    | '/explore'
    | '/foundation-icons'
    | '/lite'
    | '/people'
    | '/politics'
    | '/search'
    | '/sitemap.xml'
    | '/submit'
    | '/temples'
    | '/_authenticated/admin'
    | '/_authenticated/health'
    | '/article/$slug'
    | '/category/$category'
    | '/city/$city'
    | '/temples/$city'
    | '/forums/'
    | '/temples/'
    | '/api/public/refresh-content'
    | '/forums/thread/$threadId'
    | '/temples/temple/$slug'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssociationsRoute: typeof AssociationsRoute
  AuthRoute: typeof AuthRoute
  BayAreaIconsRoute: typeof BayAreaIconsRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  EpaperRoute: typeof EpaperRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  FoundationIconsRoute: typeof FoundationIconsRoute
  LiteRoute: typeof LiteRoute
  PeopleRoute: typeof PeopleRoute
  PoliticsRoute: typeof PoliticsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  TemplesRoute: typeof TemplesRouteWithChildren
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  CityCityRoute: typeof CityCityRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  ApiPublicRefreshContentRoute: typeof ApiPublicRefreshContentRoute
  ForumsThreadThreadIdRoute: typeof ForumsThreadThreadIdRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations': {
      id: '/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AssociationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bay-area-icons': {
      id: '/bay-area-icons'
      path: '/bay-area-icons'
      fullPath: '/bay-area-icons'
      preLoaderRoute: typeof BayAreaIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epaper': {
      id: '/epaper'
      path: '/epaper'
      fullPath: '/epaper'
      preLoaderRoute: typeof EpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation-icons': {
      id: '/foundation-icons'
      path: '/foundation-icons'
      fullPath: '/foundation-icons'
      preLoaderRoute: typeof FoundationIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite': {
      id: '/lite'
      path: '/lite'
      fullPath: '/lite'
      preLoaderRoute: typeof LiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples': {
      id: '/temples'
      path: '/temples'
      fullPath: '/temples'
      preLoaderRoute: typeof TemplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$city': {
      id: '/city/$city'
      path: '/city/$city'
      fullPath: '/city/$city'
      preLoaderRoute: typeof CityCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/': {
      id: '/temples/'
      path: '/'
      fullPath: '/temples/'
      preLoaderRoute: typeof TemplesIndexRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/temples/$city': {
      id: '/temples/$city'
      path: '/$city'
      fullPath: '/temples/$city'
      preLoaderRoute: typeof TemplesCityRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/api/public/refresh-content': {
      id: '/api/public/refresh-content'
      path: '/api/public/refresh-content'
      fullPath: '/api/public/refresh-content'
      preLoaderRoute: typeof ApiPublicRefreshContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/thread/$threadId': {
      id: '/forums/thread/$threadId'
      path: '/forums/thread/$threadId'
      fullPath: '/forums/thread/$threadId'
      preLoaderRoute: typeof ForumsThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/temple/$slug': {
      id: '/temples/temple/$slug'
      path: '/temple/$slug'
      fullPath: '/temples/temple/$slug'
      preLoaderRoute: typeof TemplesTempleSlugRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TemplesRouteChildren {
  TemplesCityRoute: typeof TemplesCityRoute
  TemplesIndexRoute: typeof TemplesIndexRoute
  TemplesTempleSlugRoute: typeof TemplesTempleSlugRoute
}

const TemplesRouteChildren: TemplesRouteChildren = {
  TemplesCityRoute: TemplesCityRoute,
  TemplesIndexRoute: TemplesIndexRoute,
  TemplesTempleSlugRoute: TemplesTempleSlugRoute,
}

const TemplesRouteWithChildren =
  TemplesRoute._addFileChildren(TemplesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AssociationsRoute: AssociationsRoute,
  AuthRoute: AuthRoute,
  BayAreaIconsRoute: BayAreaIconsRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  EpaperRoute: EpaperRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  FoundationIconsRoute: FoundationIconsRoute,
  LiteRoute: LiteRoute,
  PeopleRoute: PeopleRoute,
  PoliticsRoute: PoliticsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  TemplesRoute: TemplesRouteWithChildren,
  ArticleSlugRoute: ArticleSlugRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  CityCityRoute: CityCityRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  ApiPublicRefreshContentRoute: ApiPublicRefreshContentRoute,
  ForumsThreadThreadIdRoute: ForumsThreadThreadIdRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
